// Auto-generated. Do not edit!

// (in-package my_package.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TimerGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.timer_goal = null;
    }
    else {
      if (initObj.hasOwnProperty('timer_goal')) {
        this.timer_goal = initObj.timer_goal
      }
      else {
        this.timer_goal = {secs: 0, nsecs: 0};
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TimerGoal
    // Serialize message field [timer_goal]
    bufferOffset = _serializer.duration(obj.timer_goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TimerGoal
    let len;
    let data = new TimerGoal(null);
    // Deserialize message field [timer_goal]
    data.timer_goal = _deserializer.duration(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_package/TimerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '828ee15c33de009a08676cf4468d0ae9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal
    duration timer_goal
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TimerGoal(null);
    if (msg.timer_goal !== undefined) {
      resolved.timer_goal = msg.timer_goal;
    }
    else {
      resolved.timer_goal = {secs: 0, nsecs: 0}
    }

    return resolved;
    }
};

module.exports = TimerGoal;
