// Auto-generated. Do not edit!

// (in-package my_package.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TimerResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.timer_result = null;
      this.count = null;
    }
    else {
      if (initObj.hasOwnProperty('timer_result')) {
        this.timer_result = initObj.timer_result
      }
      else {
        this.timer_result = {secs: 0, nsecs: 0};
      }
      if (initObj.hasOwnProperty('count')) {
        this.count = initObj.count
      }
      else {
        this.count = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TimerResult
    // Serialize message field [timer_result]
    bufferOffset = _serializer.duration(obj.timer_result, buffer, bufferOffset);
    // Serialize message field [count]
    bufferOffset = _serializer.uint8(obj.count, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TimerResult
    let len;
    let data = new TimerResult(null);
    // Deserialize message field [timer_result]
    data.timer_result = _deserializer.duration(buffer, bufferOffset);
    // Deserialize message field [count]
    data.count = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 9;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_package/TimerResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2e485e994f8cdd029c0b35cee9543a6d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # result
    duration timer_result
    uint8 count
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TimerResult(null);
    if (msg.timer_result !== undefined) {
      resolved.timer_result = msg.timer_result;
    }
    else {
      resolved.timer_result = {secs: 0, nsecs: 0}
    }

    if (msg.count !== undefined) {
      resolved.count = msg.count;
    }
    else {
      resolved.count = 0
    }

    return resolved;
    }
};

module.exports = TimerResult;
