; Auto-generated. Do not edit!


(cl:in-package my_package-msg)


;//! \htmlinclude TimerResult.msg.html

(cl:defclass <TimerResult> (roslisp-msg-protocol:ros-message)
  ((timer_result
    :reader timer_result
    :initarg :timer_result
    :type cl:real
    :initform 0)
   (count
    :reader count
    :initarg :count
    :type cl:fixnum
    :initform 0))
)

(cl:defclass TimerResult (<TimerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_package-msg:<TimerResult> is deprecated: use my_package-msg:TimerResult instead.")))

(cl:ensure-generic-function 'timer_result-val :lambda-list '(m))
(cl:defmethod timer_result-val ((m <TimerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_package-msg:timer_result-val is deprecated.  Use my_package-msg:timer_result instead.")
  (timer_result m))

(cl:ensure-generic-function 'count-val :lambda-list '(m))
(cl:defmethod count-val ((m <TimerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_package-msg:count-val is deprecated.  Use my_package-msg:count instead.")
  (count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimerResult>) ostream)
  "Serializes a message object of type '<TimerResult>"
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'timer_result)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'timer_result) (cl:floor (cl:slot-value msg 'timer_result)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'count)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimerResult>) istream)
  "Deserializes a message object of type '<TimerResult>"
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'timer_result) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'count)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimerResult>)))
  "Returns string type for a message object of type '<TimerResult>"
  "my_package/TimerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimerResult)))
  "Returns string type for a message object of type 'TimerResult"
  "my_package/TimerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimerResult>)))
  "Returns md5sum for a message object of type '<TimerResult>"
  "2e485e994f8cdd029c0b35cee9543a6d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimerResult)))
  "Returns md5sum for a message object of type 'TimerResult"
  "2e485e994f8cdd029c0b35cee9543a6d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimerResult>)))
  "Returns full string definition for message of type '<TimerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%duration timer_result~%uint8 count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimerResult)))
  "Returns full string definition for message of type 'TimerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%duration timer_result~%uint8 count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimerResult>))
  (cl:+ 0
     8
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TimerResult
    (cl:cons ':timer_result (timer_result msg))
    (cl:cons ':count (count msg))
))
