; Auto-generated. Do not edit!


(cl:in-package my_package-msg)


;//! \htmlinclude TimerFeedback.msg.html

(cl:defclass <TimerFeedback> (roslisp-msg-protocol:ros-message)
  ((timer_feedback
    :reader timer_feedback
    :initarg :timer_feedback
    :type cl:real
    :initform 0)
   (count_feedback
    :reader count_feedback
    :initarg :count_feedback
    :type cl:fixnum
    :initform 0))
)

(cl:defclass TimerFeedback (<TimerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_package-msg:<TimerFeedback> is deprecated: use my_package-msg:TimerFeedback instead.")))

(cl:ensure-generic-function 'timer_feedback-val :lambda-list '(m))
(cl:defmethod timer_feedback-val ((m <TimerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_package-msg:timer_feedback-val is deprecated.  Use my_package-msg:timer_feedback instead.")
  (timer_feedback m))

(cl:ensure-generic-function 'count_feedback-val :lambda-list '(m))
(cl:defmethod count_feedback-val ((m <TimerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_package-msg:count_feedback-val is deprecated.  Use my_package-msg:count_feedback instead.")
  (count_feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimerFeedback>) ostream)
  "Serializes a message object of type '<TimerFeedback>"
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'timer_feedback)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'timer_feedback) (cl:floor (cl:slot-value msg 'timer_feedback)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'count_feedback)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimerFeedback>) istream)
  "Deserializes a message object of type '<TimerFeedback>"
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'timer_feedback) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'count_feedback)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimerFeedback>)))
  "Returns string type for a message object of type '<TimerFeedback>"
  "my_package/TimerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimerFeedback)))
  "Returns string type for a message object of type 'TimerFeedback"
  "my_package/TimerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimerFeedback>)))
  "Returns md5sum for a message object of type '<TimerFeedback>"
  "32d8cea043f28b962042d445c5824043")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimerFeedback)))
  "Returns md5sum for a message object of type 'TimerFeedback"
  "32d8cea043f28b962042d445c5824043")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimerFeedback>)))
  "Returns full string definition for message of type '<TimerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%duration timer_feedback~%uint8 count_feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimerFeedback)))
  "Returns full string definition for message of type 'TimerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%duration timer_feedback~%uint8 count_feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimerFeedback>))
  (cl:+ 0
     8
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TimerFeedback
    (cl:cons ':timer_feedback (timer_feedback msg))
    (cl:cons ':count_feedback (count_feedback msg))
))
