; Auto-generated. Do not edit!


(cl:in-package my_package-msg)


;//! \htmlinclude TimerGoal.msg.html

(cl:defclass <TimerGoal> (roslisp-msg-protocol:ros-message)
  ((timer_goal
    :reader timer_goal
    :initarg :timer_goal
    :type cl:real
    :initform 0))
)

(cl:defclass TimerGoal (<TimerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_package-msg:<TimerGoal> is deprecated: use my_package-msg:TimerGoal instead.")))

(cl:ensure-generic-function 'timer_goal-val :lambda-list '(m))
(cl:defmethod timer_goal-val ((m <TimerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_package-msg:timer_goal-val is deprecated.  Use my_package-msg:timer_goal instead.")
  (timer_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimerGoal>) ostream)
  "Serializes a message object of type '<TimerGoal>"
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'timer_goal)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'timer_goal) (cl:floor (cl:slot-value msg 'timer_goal)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimerGoal>) istream)
  "Deserializes a message object of type '<TimerGoal>"
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'timer_goal) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimerGoal>)))
  "Returns string type for a message object of type '<TimerGoal>"
  "my_package/TimerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimerGoal)))
  "Returns string type for a message object of type 'TimerGoal"
  "my_package/TimerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimerGoal>)))
  "Returns md5sum for a message object of type '<TimerGoal>"
  "828ee15c33de009a08676cf4468d0ae9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimerGoal)))
  "Returns md5sum for a message object of type 'TimerGoal"
  "828ee15c33de009a08676cf4468d0ae9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimerGoal>)))
  "Returns full string definition for message of type '<TimerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%duration timer_goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimerGoal)))
  "Returns full string definition for message of type 'TimerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%duration timer_goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimerGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TimerGoal
    (cl:cons ':timer_goal (timer_goal msg))
))
