// Generated by gencpp from file my_package/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_ADDTWOINTS_H
#define MY_PACKAGE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <my_package/AddTwoIntsRequest.h>
#include <my_package/AddTwoIntsResponse.h>


namespace my_package
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace my_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_package::AddTwoInts > {
  static const char* value()
  {
    return "713e5cf1444846805670f946f08bfc96";
  }

  static const char* value(const ::my_package::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::my_package::AddTwoInts > {
  static const char* value()
  {
    return "my_package/AddTwoInts";
  }

  static const char* value(const ::my_package::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::my_package::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::my_package::AddTwoInts > 
template<>
struct MD5Sum< ::my_package::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::AddTwoInts >::value();
  }
  static const char* value(const ::my_package::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::AddTwoIntsRequest> should match 
// service_traits::DataType< ::my_package::AddTwoInts > 
template<>
struct DataType< ::my_package::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::my_package::AddTwoInts >::value();
  }
  static const char* value(const ::my_package::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_package::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::my_package::AddTwoInts > 
template<>
struct MD5Sum< ::my_package::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::AddTwoInts >::value();
  }
  static const char* value(const ::my_package::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::AddTwoIntsResponse> should match 
// service_traits::DataType< ::my_package::AddTwoInts > 
template<>
struct DataType< ::my_package::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::my_package::AddTwoInts >::value();
  }
  static const char* value(const ::my_package::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_ADDTWOINTS_H
